#!/usr/bin/env python

"""Usage: pontoon region list [--help]

Options:
    -h --help       Show this page.
"""

from pontoon import ui
from pontoon import Command
from pontoon import RegionException


class RegionCommand(Command):

    def list(self):
        available = self.pontoon.region.list()
        ui.message("Available regions:")
        for r in available:
            ui.message(" - %s" % r.name)
        return 0


if __name__ == '__main__':

    try:
        cmd = RegionCommand(str(__doc__))
        exit(cmd.run())
    except RegionException as e:
        ui.message(str(e))
        exit(1)

    exit(0)
